# Generated by Django 4.1.7 on 2023-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_identifier', models.CharField(max_length=25)),
                ('reference_date', models.DateField()),
                ('type', models.CharField(max_length=86)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25, unique=True)),
                ('issue_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('rating', models.IntegerField()),
                ('maturity_date', models.DateField()),
                ('total_expected_interest_amount', models.FloatField()),
                ('invested_amount', models.FloatField(default=0)),
                ('investment_date', models.DateField(null=True)),
                ('expected_interest_amount', models.FloatField(default=0)),
                ('expected_irr', models.FloatField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('realized_irr', models.FloatField(default=0)),
            ],
        ),
    ]
